# Generated by Django 3.1.2 on 2020-11-14 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20201113_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceclass',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AssignmentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('maxmarks', models.IntegerField()),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.assign')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2018-10-23')),
                ('marks', models.IntegerField()),
                ('assignmentclass', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.assignmentclass')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.student')),
            ],
        ),
    ]
